@HotelListing.Api_HostAddress = https://localhost:7058

###### Hotels API ######

GET {{HotelListing.Api_HostAddress}}/api/hotels
Accept: application/json

###

GET {{HotelListing.Api_HostAddress}}/api/hotels/3
Accept: application/json

###
POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "name": "Hotel One",
  "address": "789 Oak St",
  "phoneNumber": "555-9012",
  "rating": 3.4,
  "countryId": 1
}

###

@id=3
PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "Id": 3,
  "name": "Hotel Five",
  "address": "Amman",
  "phoneNumber": "123-548",
  "rating": 4.4,
  "countryId": 1
}


###

DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###### Countries API ######

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "Jordan",
  "shortName": "JO"
}

###

GET {{HotelListing.Api_HostAddress}}/api/countries

###

